version: '2'

services:
  web:
    image: nginx:latest
    hostname: arthur.dev
    volumes:
      - ./docker/nginx/conf/arthur.conf:/etc/nginx/conf.d/default.conf
      - ~/Projects:/var/www/vhosts
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - arthur-network

  php:
    build: ./docker/php
    volumes:
      - ./docker/php/conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ~/Projects:/var/www/vhosts
    restart: always
    networks:
      - arthur-network

  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
      - /var/lib/mysql
    restart: always
    networks:
      - arthur-network

networks:
  arthur-network:
    driver: bridge
